-- Ghostea database schema
-- Run this once in Supabase SQL Editor.
-- The application uses the server-side SUPABASE_KEY only.
-- Never expose that key in the Vercel browser bundle.

create table if not exists ghostea_group_settings (
    chat_id bigint primary key,
    max_warnings integer not null default 3,
    mute1_minutes integer not null default 2,
    mute2_minutes integer not null default 5,
    flood_window_seconds integer not null default 8,
    flood_message_limit integer not null default 6,
    flood_mute_minutes integer not null default 10,
    blocked_link_action text not null default 'delete',
    abuse_filter_enabled boolean not null default true,
    spam_filter_enabled boolean not null default true,
    link_filter_enabled boolean not null default true,
    flood_protection_enabled boolean not null default true,
    welcome_enabled boolean not null default true,
    antiraid_enabled boolean not null default true,
    antiraid_join_limit integer not null default 8,
    antiraid_window_seconds integer not null default 20,
    antiraid_lock_minutes integer not null default 10,
    auto_cleanup_enabled boolean not null default false,
    verification_enabled boolean not null default true,
    verification_timeout_seconds integer not null default 120,
    min_account_age_days integer not null default 0,
    new_member_restriction_minutes integer not null default 0,
    repeated_message_window_seconds integer not null default 60,
    repeated_message_limit integer not null default 3,
    mention_spam_limit integer not null default 6,
    max_message_length integer not null default 4000,
    warning_decay_enabled boolean not null default true,
    warning_decay_days integer not null default 30,
    cleanup_max_age_days integer not null default 30,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists ghostea_warnings (
    chat_id bigint not null,
    user_id bigint not null,
    count integer not null default 0,
    updated_at timestamptz not null default now(),
    primary key (chat_id, user_id)
);

create table if not exists ghostea_warning_history (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    user_id bigint not null,
    reason text not null,
    source text not null,
    created_at timestamptz not null default now()
);
create index if not exists idx_ghostea_warning_history_chat_user
on ghostea_warning_history(chat_id, user_id, created_at desc);

create table if not exists ghostea_custom_filters (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    filter_type text not null,
    value text not null,
    enabled boolean not null default true,
    created_at timestamptz not null default now(),
    unique(chat_id, filter_type, value)
);

create table if not exists ghostea_moderation_logs (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    user_id bigint,
    action text not null,
    reason text,
    details text,
    created_at timestamptz not null default now()
);
create index if not exists idx_ghostea_moderation_logs_chat
on ghostea_moderation_logs(chat_id, created_at desc);

create table if not exists ghostea_join_events (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    user_id bigint not null,
    joined_at timestamptz not null default now()
);
create index if not exists idx_ghostea_join_events_chat
on ghostea_join_events(chat_id, joined_at desc);

create table if not exists ghostea_raid_events (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    action text not null,
    details text,
    created_at timestamptz not null default now()
);

create table if not exists ghostea_verifications (
    chat_id bigint not null,
    user_id bigint not null,
    token text not null,
    expires_at timestamptz not null,
    verified boolean not null default false,
    created_at timestamptz not null default now(),
    primary key(chat_id, user_id)
);

create table if not exists ghostea_reputation (
    chat_id bigint not null,
    user_id bigint not null,
    score integer not null default 0,
    positive_actions integer not null default 0,
    negative_actions integer not null default 0,
    updated_at timestamptz not null default now(),
    primary key(chat_id, user_id)
);

create table if not exists ghostea_cleanup_runs (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    cutoff_at timestamptz not null,
    deleted_count integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists ghostea_health_events (
    id bigint generated by default as identity primary key,
    chat_id bigint,
    status text not null,
    details text,
    created_at timestamptz not null default now()
);
create index if not exists idx_ghostea_health_events_time
on ghostea_health_events(created_at desc);

-- ============================================================
-- Ghostea Phase 10 — User management audit trail
-- ============================================================
create table if not exists ghostea_user_admin_actions (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    target_user_id bigint not null,
    admin_user_id bigint,
    action text not null,
    details text,
    created_at timestamptz not null default now()
);

create index if not exists idx_ghostea_user_admin_actions_chat
on ghostea_user_admin_actions(chat_id, created_at desc);

create index if not exists idx_ghostea_user_admin_actions_target
on ghostea_user_admin_actions(chat_id, target_user_id, created_at desc);


-- ============================================================
-- Ghostea Phase 11 — Persistent security/recovery state
-- ============================================================
create table if not exists ghostea_security_locks (
    chat_id bigint not null,
    lock_type text not null,
    expires_at timestamptz not null,
    original_permissions jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    primary key (chat_id, lock_type)
);

create index if not exists idx_ghostea_security_locks_expiry
on ghostea_security_locks(expires_at);
